spring:
  application:
    name: @pom.artifactId@

  #  profiles:
  #    active: dev

  profiles:
    include:
      - admin
      - endpoint
      - ezviz
      - file
      - hikari
      - logging
#      - mail
      - minio
      - mvn
      - mybatis
      - mysql
      - oss
      - protocol
      - redis
      - security
      - ${spring.application.name}-dynamic