springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '全部模块'
      paths-to-match: '/**'
      packages-to-scan: com.ronnaces.ronna.boot
    - group: '系统模块'
      paths-to-match: '/**'
      packages-to-scan: com.ronnaces.ronna.boot.system
    - group: '系统组件模块'
      paths-to-match: '/**'
      packages-to-scan: com.ronnaces.ronna.boot.system.component
    - group: '系统管理模块'
      paths-to-match: '/**'
      packages-to-scan: com.ronnaces.ronna.boot.system.management
knife4j:
  enable: true
  setting:
    language: zh_cn