spring:
  boot:
    admin:
      monitor:
        default-timeout: 30000
      context-path: "/admin"
      client:
        enabled: true
        url: "http://localhost:${server.port}/admin"
        instance:
          service-url: "http://localhost:${server.port}"
        username: "admin"
        password: "admin"