spring:
  data:
    redis:
      host: localhost
      #      host: 192.168.81.128
      #    host: redis.ronnaces
      #      port: 30003
      port: 6379
      password: nogx3PIHiZm5pBsf
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 5
          max-wait: -1ms