spring:
  application:
    name: @pom.artifactId@

  profiles:
    active: dev

#    include:
#      - admin
#      - api
#      - endpoint
#      - file
#      - hikari
#      - logging
#      - mvc
#      - mybatis
#      - mysql
#      - oss
#      - redis
#      - security
#      - ${spring.application.name}-dynamic

