spring:
  datasource:
    hikari:
      pool-name: HikariCP
      autoCommit: true
      idle-timeout: 180000
      connection-timeout: 30000
      keepalive-time: 30000
      max-lifetime: 1800000
      minimum-idle: 10
      maximum-pool-size: 10
      connection-test-query: SELECT 1
