server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:ronna.ronnaces.com.jks
    key-store-password: 3jtu6kub
    key-store-type: JKS

loong:
  log:
    enable: true
  files:
    data: "./data"
  auth:
    permits:
      - "/actuator/**"
      - "/v1/auth/**"
      - "/admin/**"
      - "/instances/**"
      - "/webjars/**"
      - "/images/**"
      - "/css/**"
      - "/**.html"
      - "/**.css"
      - "/doc.html"
      - "/v3/api-docs/**"
      - "/v3/**"
      - "/swagger-resources/**"
      - "/swagger-ui/**"
      - "/swagger-ui.html"
      - "/favicon.ico"

    defaultPassword: "88888888"
    accessTokenExpire: 100000
    refreshTokenExpire: 100000

springdoc:
  group-configs:
    - group: '全部模块'
      paths-to-match: '/**'
      packages-to-scan: com.ronnaces.ronna.boot
    - group: '系统模块'
      paths-to-match: '/**'
      packages-to-scan: com.ronnaces.ronna.boot.system.modules