springdoc:
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '全部模块'
      paths-to-match: '/**'
      packages-to-scan: com.ronnaces.ronna.boot
    - group: '基础组件模块'
      paths-to-match: '/**'
      packages-to-scan: com.ronnaces.ronna.boot.infrastructure
    - group: '系统管理模块'
      paths-to-match: '/**'
      packages-to-scan: com.ronnaces.ronna.boot.system.modules

  info:
    title: ${spring.application.name} - API
    version: 3.0.0
    description: 接口文档
    contact:
      name: "luokunlong"
      url: ""
      email: "luokunlong.loong@gmail.com"
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html

knife4j:
  enable: true
  setting:
    language: zh_cn

  basic:
    enable: true
    username: admin
    password: admin