spring:
  servlet:
    multipart:
      #      enabled: true
      #      location: file:${loong.file.upload}
      # 单个文件最大值
      max-file-size: 100MB
      # 单次上传文件最大值
      max-request-size: 1GB

loong:
  files:
    upload: "./data/files"
    camera:
      upload: "./data/files/camera"

